#ifndef PROTOCOL_H
#define PROTOCOL_H

#define LOAD_PROTOCOL_VERSION 1
#define DEFAULT_HOST_COUNT 100
#define DEFAULT_CONNECT_TIMEOUT_MS 2000
#define DEFAULT_IO_TIMEOUT_MS 2000
#define DEFAULT_CANDIDATE_PORT_START 20000
#define DEFAULT_CANDIDATE_PORT_END 20999

#define DEFAULT_HOSTS_FILE "run/hosts.txt"
#define DEFAULT_MANIFEST_FILE "run/manifest.env"

#define LOAD_RESPONSE_FIELDS 3
#define LOAD_RESPONSE_SIZE 128

#endif